name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: yarn
      - name: Test
        run: yarn test:coverage
      - name: Coverage
        uses: codecov/codecov-action@v4
